version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - nodeapi
    ports:
      - "3000:80"
    # links:
    #   - "nodeapi:api"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # networks:
    #   - nest-api-net
  nodeapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #  - '8080:3000'
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    # networks:
    #   - nest-api-net
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    container_name: ${DATABASE_HOST}
    ports:
      - '3310:3306'
    # networks:
    #   - nest-api-net

# networks:
#   nest-api-net:
#     driver: bridge
